name: test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.0.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  provider: ^6.0.2
  google_sign_in: ^5.2.4
  flutter_svg: ^1.0.3
  flutter_native_splash: ^2.1.1
  http: ^0.13.4
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  color: "#F1F1F1"
  image: images/logo_temp.png
  android: true
  ios: true

#flutter_icons:
#  image_path: "images/logo_temp.png"
#  android: true
#  ios: true

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/Cabin.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/Comfortaa.ttf
    - family: Lato
      fonts:
        - asset: assets/Lato.ttf


  assets:
    - images/
    - lib/screens/moods/burnt_out/burnt_out_article_json.json
    - lib/screens/moods/burnt_out/burnt_out_article_json.json
